spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/clc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: kabilstudies1999@gmail.com
    password: zioa avrj lxjx jpjp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
app:
  default-admin-password: admin2025
  restore-script-path: D:\wamp64\www\FinalYearProject\CLC-Api\src\main\resources\restore\restore.bat
